version: "2"

services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper

  kafka:
    hostname: kafka
    image: wurstmeister/kafka:2.12-2.4.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka

  scripts:
    build:
      context: ./scripts
